In [1]:
print("hi")

hi


In [2]:
import torch
from torch import nn

In [3]:

inputs = torch.Tensor([[[0.2, 0.1, 0.3], [0.5, 0.1, 0.1]]])
B, S, E = inputs.size()
inputs = inputs.reshape(S, B, E)
inputs.size()

torch.Size([2, 1, 3])

In [11]:
inputs

tensor([[[0.2000, 0.1000, 0.3000]],

        [[0.5000, 0.1000, 0.1000]]])

In [4]:

parameter_shape = inputs.size()[-2:]
gamma = nn.Parameter(torch.ones(parameter_shape))
beta =  nn.Parameter(torch.zeros(parameter_shape))

In [5]:

gamma.size(), beta.size()

(torch.Size([1, 3]), torch.Size([1, 3]))

In [8]:
len(parameter_shape)

2

In [6]:

dims = [-(i + 1) for i in range(len(parameter_shape))]

In [7]:
dims

[-1, -2]

In [9]:
mean = inputs.mean(dim=dims, keepdim=True)
mean.size()

torch.Size([2, 1, 1])

In [10]:
mean

tensor([[[0.2000]],

        [[0.2333]]])

In [12]:

var = ((inputs - mean) ** 2).mean(dim=dims, keepdim=True)
epsilon = 1e-5
std = (var + epsilon).sqrt()
std

tensor([[[0.0817]],

        [[0.1886]]])

In [13]:

y = (inputs - mean) / std
y


tensor([[[ 0.0000, -1.2238,  1.2238]],

        [[ 1.4140, -0.7070, -0.7070]]])

In [14]:
out = gamma * y + beta

In [15]:

out

tensor([[[ 0.0000, -1.2238,  1.2238]],

        [[ 1.4140, -0.7070, -0.7070]]], grad_fn=<AddBackward0>)

Class

In [16]:
import torch
from torch import nn

class LayerNormalization():
    def __init__(self, parameters_shape, eps=1e-5):
        self.parameters_shape=parameters_shape
        self.eps=eps
        self.gamma = nn.Parameter(torch.ones(parameters_shape))
        self.beta =  nn.Parameter(torch.zeros(parameters_shape))

    def forward(self, input):
        dims = [-(i + 1) for i in range(len(self.parameters_shape))]
        mean = inputs.mean(dim=dims, keepdim=True)
        print(f"Mean \n ({mean.size()}): \n {mean}")
        var = ((inputs - mean) ** 2).mean(dim=dims, keepdim=True)
        std = (var + self.eps).sqrt()
        print(f"Standard Deviation \n ({std.size()}): \n {std}")
        y = (inputs - mean) / std
        print(f"y \n ({y.size()}) = \n {y}")
        out = self.gamma * y  + self.beta
        print(f"out \n ({out.size()}) = \n {out}")
        return out

In [17]:

batch_size = 3
sentence_length = 5
embedding_dim = 8 
inputs = torch.randn(sentence_length, batch_size, embedding_dim)

print(f"input \n ({inputs.size()}) = \n {inputs}")
     

input 
 (torch.Size([5, 3, 8])) = 
 tensor([[[-0.9742,  0.0067,  0.0895,  0.2329, -0.7710,  0.9704,  1.2548,
          -1.2793],
         [ 2.0400, -1.2043, -1.0021,  1.5777,  0.1094, -2.0955,  1.6636,
           0.6327],
         [-0.0279,  2.3153, -0.1369, -0.0789, -0.0974, -2.6111,  0.2641,
          -0.5401]],

        [[-1.3825,  1.6292, -0.4429, -0.1024,  1.4118,  0.7589, -2.0651,
           0.2362],
         [-0.1873, -0.8584,  2.1499,  0.5765, -1.4537,  1.4295,  0.3324,
          -1.4336],
         [-0.8193,  0.2769, -0.5915,  0.2476,  0.2662, -0.2236, -0.8932,
           0.5925]],

        [[ 0.7938,  0.2267,  0.7159,  1.4026,  0.0135,  0.1012, -1.1711,
          -0.2817],
         [-0.3826, -0.1480,  1.0435,  0.1243, -0.7556, -1.1253,  2.4579,
           1.0990],
         [-0.1113,  0.7140, -0.7018, -2.0093, -0.6113,  0.6399,  0.1015,
          -0.0721]],

        [[ 1.1426, -0.9202,  1.7040,  2.0868,  0.7310, -0.6680,  1.1511,
          -0.6991],
         [-0.8450, -0.7598, 

In [24]:
layer_norm = LayerNormalization(inputs.size()[-1:])

In [26]:
out = layer_norm.forward(inputs)

Mean 
 (torch.Size([5, 3, 1])): 
 tensor([[[-0.0588],
         [ 0.2152],
         [-0.1141]],

        [[ 0.0054],
         [ 0.0694],
         [-0.1430]],

        [[ 0.2251],
         [ 0.2891],
         [-0.2563]],

        [[ 0.5660],
         [-1.0516],
         [ 0.5600]],

        [[-0.0187],
         [-0.1942],
         [ 0.5515]]])
Standard Deviation 
 (torch.Size([5, 3, 1])): 
 tensor([[[0.8464],
         [1.4277],
         [1.2486]],

        [[1.2073],
         [1.2253],
         [0.5321]],

        [[0.7260],
         [1.1006],
         [0.8159]],

        [[1.0978],
         [0.5576],
         [0.7436]],

        [[1.0333],
         [0.8219],
         [0.9773]]])
y 
 (torch.Size([5, 3, 8])) = 
 tensor([[[-1.0815e+00,  7.7319e-02,  1.7514e-01,  3.4460e-01, -8.4149e-01,
           1.2160e+00,  1.5520e+00, -1.4420e+00],
         [ 1.2782e+00, -9.9424e-01, -8.5265e-01,  9.5437e-01, -7.4079e-02,
          -1.6185e+00,  1.0145e+00,  2.9241e-01],
         [ 6.9034e-02,  1.9458e